events{}

http{
	upstream myapp{
		server app-blue:80; #this will be modified by script
	}
	
	server{
		listen 80;
		server_name localhost;

		location / {
			proxy_pass http://myapp;
			proxy_set_header HOST $host;
			proxy_set_header X-Real-IP $remote_addr;
		}
	}
}

